# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Life < Formula
  desc "Personal knowledge system — markdown in, structured data out"
  homepage "https://github.com/jakenolan/life-sdk"
  version "0.1.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.17/life_0.1.17_darwin_amd64.tar.gz"
      sha256 "7034e58ecd0701ad4610dc096e5f5df9ad783af84dfb3212a785a3573aeb0969"

      define_method(:install) do
        bin.install "life"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.17/life_0.1.17_darwin_arm64.tar.gz"
      sha256 "14c7edf61b9b5edea8dc2aa953cb0f40d413ce7944599aa10b7f9170f9df8656"

      define_method(:install) do
        bin.install "life"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.17/life_0.1.17_linux_amd64.tar.gz"
      sha256 "6279f0cb9d798546aecb0e77a518f7e8a61c0b39a60c1c820ae8524a9e1c9d47"
      define_method(:install) do
        bin.install "life"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.17/life_0.1.17_linux_arm64.tar.gz"
      sha256 "e63c4e34619f6b267d01f3f6641fe4e25dd7bf67480c95320886e9c118a93e67"
      define_method(:install) do
        bin.install "life"
      end
    end
  end

  def caveats
    <<~EOS
      Life Library runs a background service managed by launchd (macOS) or
      systemd (Linux). Before uninstalling, stop the service to avoid leaving
      an orphaned registration:

        life service stop
        brew uninstall life

      Your data (~/.life/, keychain, database) is preserved on uninstall.
      To also remove your data before uninstalling, run: life reset
    EOS
  end

  test do
    system "#{bin}/life", "version"
  end
end
