# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Life < Formula
  desc "Personal knowledge system — markdown in, structured data out"
  homepage "https://github.com/jakenolan/life-sdk"
  version "0.1.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.18/life_0.1.18_darwin_amd64.tar.gz"
      sha256 "093c7b6a2027da584b22e8bb82af77fdddaf279981f4e99dd0197b28b53a25a5"

      define_method(:install) do
        bin.install "life"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.18/life_0.1.18_darwin_arm64.tar.gz"
      sha256 "dcf3e9b0095171c4f1a86a30ac56e754ab9a5dedeea24a1d2861e51adaf5e182"

      define_method(:install) do
        bin.install "life"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.18/life_0.1.18_linux_amd64.tar.gz"
      sha256 "89eb26767444368ab258e8dcc4ec7fcd5f3d573ea13d16568097bdcfb1ff3633"
      define_method(:install) do
        bin.install "life"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.18/life_0.1.18_linux_arm64.tar.gz"
      sha256 "161e01196fdfce05a555846d366a39a39911c112af38c6a2e6373eb6acfede45"
      define_method(:install) do
        bin.install "life"
      end
    end
  end

  def caveats
    <<~EOS
      Life Library runs a background service managed by launchd (macOS) or
      systemd (Linux). Before uninstalling, stop the service to avoid leaving
      an orphaned registration:

        life service stop
        brew uninstall life

      Your data (~/.life/, keychain, database) is preserved on uninstall.
      To also remove your data before uninstalling, run: life reset
    EOS
  end

  test do
    system "#{bin}/life", "version"
  end
end
