# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Life < Formula
  desc "Personal knowledge system — markdown in, structured data out"
  homepage "https://github.com/jakenolan/life-sdk"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.3/life_0.1.3_darwin_amd64.tar.gz"
      sha256 "6299b415145915f6a69059e56c2316d29565c7597629e307788d9e2bf865076d"

      define_method(:install) do
        bin.install "life"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.3/life_0.1.3_darwin_arm64.tar.gz"
      sha256 "0e3f01e9edad28087f42e656fb96f284bdcc268fcac4c0b643501270c704857a"

      define_method(:install) do
        bin.install "life"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.3/life_0.1.3_linux_amd64.tar.gz"
      sha256 "6b98e1d08e048894fa872d0ff14b49b5f9e53ecca246f94f9932d2e4d8cd21e8"
      define_method(:install) do
        bin.install "life"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakenolan/life-sdk/releases/download/v0.1.3/life_0.1.3_linux_arm64.tar.gz"
      sha256 "7ce5be7f74824d564617a8b7878da5cbb3a7079204cd1ab395fc77d138d0c90b"
      define_method(:install) do
        bin.install "life"
      end
    end
  end

  test do
    system "#{bin}/life", "version"
  end
end
